import subprocess
import time
import os
import re
import glob
import numpy as np
import Y
import pdfgen


'''
This is the main pipeline for calculating the PDF of DM from FRBs on "Marvin HPC". It consists of five stages:
1. Run the first bash script to calculate the spectrum DM(M,z,theta) and vectorize it, as well as vectorize the angular halo density and halo bias function.
2. Wait for the first stage to finish and the output files to be generated.
3. Run the second bash script to calculate the PDF of DM from the output of the first stage.
4. Clean up the intermediate files generated by the first stage to save disk space.
5. Return the final PDF and the corresponding DM values (plambda) as numpy arrays and save them to disk.
'''

# Configuration

script_path = './job.sh'
second_script = "./Y.sh"

# Run the bash script with the two parameters

def run_first_stage(params):
    subprocess.run(['bash', script_path, str(params[0]), str(params[1]), str(params[2]), str(params[3]), str(params[4]), str(params[5]), str(params[6]), str(params[7]), str(params[8]), str(params[9]), str(params[10]), str(params[11]), str(params[12]), str(params[13]), str(params[14])], capture_output=True, text=True)
   
def wait_for_npy(file, timeout=9000): 
    start_time = time.time()
    while time.time() - start_time < timeout:
        # Check if the 'spectrum.npy' file exists in the directory
        spectrum_file = os.path.join("10", file)
        if os.path.isfile(spectrum_file):
            #print(f"{file} has been generated!")
            time.sleep(1)
            return
        # If file doesn't exist, wait for 1 seconds before checking again
        time.sleep(1)
    # Raise a TimeoutError if the file isn't found within the timeout period
    raise TimeoutError(f"Timed out waiting for 'spectrum.npy' in 10/.")

def wait_for_process(name):
    while True:
        files = glob.glob(name+"-*")
        if files:
            break
        time.sleep(1) 


def run_second_stage():
    subprocess.run(['sbatch', second_script], capture_output=True,text=True)

def garbage():
    files_to_remove = glob.glob("10/*") + glob.glob("spectrum.sh") + glob.glob("spectrumslurm-*")
    # Remove each file
    for file in files_to_remove:
        os.remove(file)


def run_pipeline(params):
    """Executes the full pipeline for given parameters and returns final values."""
    try:
        run_first_stage(params)
    except:
        print("spectrum error")
        pass
    wait_for_process('spectrumslurm') 
    #os.remove(glob.glob("slurm-*")[0])
    try:
        wait_for_npy("Y.npy")
    except:
        print("spectum does not exist")
        return np.full(1000,np.nan)
    Y.data_generator(params[0:6]).Yvec()
    wait_for_npy("hb.npy")
    try:
        pdf, plambda = pdfgen.final_result(params[0:6])
        try:
            print('hi')
            garbage()
        except:
            pass
        return pdf, plambda
    except Exception as e:
        print("pdfgen error:", e)
        return np.full(1000, np.nan), np.full(1000, np.nan)

if __name__ == "__main__":
    """
    par = [cosmological parameters, redshift, BFC parameters]
        = [Om,Ob,s8,ns,h0,z,eta,deta,Nstar,ciga,thco,Mc,mu,delta,gamma]
    """
    par = [0.3089,0.0486,0.8159,0.9667,0.6774,0.6,
           0.017,0.229,0.0074,0.0093,0.231,10**12.86,.721,5.47,1.5]
    pdf, plambda = run_pipeline(par)
    np.save(f'data/pdf_ref.npy',pdf)
    np.save(f'data/p_ref.npy',plambda)
